remedial2/core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns = [

    ##urls jugador
    path('lista/jugador/',views.listajugadores.as_view(), name="listajugadores"),
    path('crear/jugador/',views.crearjugador.as_view(), name="crearjugador"),
    path('detalles/jugador/<int:pk>/', views.detallesjugador.as_view(), name= "detallesjugador"),
    path('actualizar/jugador/<int:pk>/', views.actuajugador.as_view(), name= "actujugador"),
    path('borrar/jugador/<int:pk>/', views.borrarjugador.as_view(), name= "borrarjugador"),

    ##urls equipos
    path('lista/equipo/',views.listaequipos.as_view(), name="listaequipos"),
    path('crear/equipo/',views.crearequipos.as_view(), name="crearequipo"),
    path('detalles/equipo/<int:pk>/', views.detallesquipo.as_view(), name= "detallesequipo"),
    path('actualizar/equipo/<int:pk>/', views.actuequipo.as_view(), name= "actuequipo"),
    path('borrar/equipo/<int:pk>/', views.borrarequipo.as_view(), name= "borrarequipo"),

    ##urls estadios
    path('lista/estadio/',views.listaestadios.as_view(), name="listaestadios"),
    path('crear/estadio/',views.crearestadio.as_view(), name="crearestadio"),
    path('detalles/estadio/<int:pk>/', views.detallesestadio.as_view(), name= "detallesestadio"),
    path('actualizar/estadio/<int:pk>/', views.actuestadio.as_view(), name= "actuestadio"),
    path('borrar/estadio/<int:pk>/', views.borrarestadio.as_view(), name= "borrarestadio"),
]

remedial2/nfl_red2/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls'))

]

remedial2/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    
    
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">NFL RAY</a>
      <nav class=" " >
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">

      </nav>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaequipos' %}">Equipos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listajugadores' %}">Jugadores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:listaestadios' %}">Estadios</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <footer class="bg-light text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      ©2023 Copyright:
      <a class="text-dark" href="https://gitlab.com/03f_repositorio/remedial_2">Repositorio.com</a>
    </div>
    <!-- Copyright -->
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>