remedial2/core/urls.py
from django.urls import path
from core import views

app_name="core"
urlpatterns = [

    ##urls jugador
    path('lista/jugador/',views.listajugadores.as_view(), name="listajugadores"),
    path('crear/jugador/',views.crearjugador.as_view(), name="crearjugador"),
    path('detalles/jugador/<int:pk>/', views.detallesjugador.as_view(), name= "detallesjugador"),
    path('actualizar/jugador/<int:pk>/', views.actuajugador.as_view(), name= "actujugador"),
    path('borrar/jugador/<int:pk>/', views.borrarjugador.as_view(), name= "borrarjugador"),

    ##urls equipos
    path('lista/equipo/',views.listaequipos.as_view(), name="listaequipos"),
    path('crear/equipo/',views.crearequipos.as_view(), name="crearequipo"),
    path('detalles/equipo/<int:pk>/', views.detallesquipo.as_view(), name= "detallesequipo"),
    path('actualizar/equipo/<int:pk>/', views.actuequipo.as_view(), name= "actuequipo"),
    path('borrar/equipo/<int:pk>/', views.borrarequipo.as_view(), name= "borrarequipo"),

    ##urls estadios
    path('lista/estadio/',views.listaestadios.as_view(), name="listaestadios"),
    path('crear/estadio/',views.crearestadio.as_view(), name="crearestadio"),
    path('detalles/estadio/<int:pk>/', views.detallesestadio.as_view(), name= "detallesestadio"),
    path('actualizar/estadio/<int:pk>/', views.actuestadio.as_view(), name= "actuestadio"),
    path('borrar/estadio/<int:pk>/', views.borrarestadio.as_view(), name= "borrarestadio"),
]

remedial2/nfl_red2/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls'))

]

remedial2/core/models.py
from django.db import models

class Equipo(models.Model):
    nombre = models.CharField(max_length=50)
    evento = models.CharField(max_length=254)
    propietario = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre 


class Jugador (models.Model):
    nombre = models.CharField(max_length=50)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    posicion = models.CharField(max_length=50)
    numero = models.IntegerField()
    def __str__(self):
        return self.nombre 
    
class Estadio(models.Model): 
    nombre = models.CharField(max_length=50)
    capacidad = models.IntegerField()
    espacio = models.CharField
    equipos=models.ForeignKey(Equipo, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre 

remedial2/core/forms.py
from django import forms
from .models import *

##jugador
class jugadorforms (forms.ModelForm):
    class Meta:
        model = Jugador
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del jugador"}),
            "equipos": forms.Select(attrs={"class":"form-select form-control"}),
            "posicion": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Posicion del jugador"}),
            "numero":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Numero del jugador"}),
        }


class actujugadorforms (forms.ModelForm):
    class Meta:
        model = Jugador
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del jugador"}),
            "equipos": forms.Select(attrs={"class":"form-select form-control"}),
            "posicion": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Posicion del jugador"}),
            "numero":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Numero del jugador"}),
        }
        
#Equipo 
class crearequipoforms (forms.ModelForm):
    class Meta:
        model = Equipo
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del equipo"}),
            "evento":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Evento"}),
            "propietario": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Nombre del propietario"}),
            }



class actuequipoforms (forms.ModelForm):
    class Meta:
        model = Equipo
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del equipo"}),
            "evento":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Evento"}),
            "propietario": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Nombre del propietario"}),
            }



#Estadio 
class crearestadioforms (forms.ModelForm):
    class Meta:
        model = Equipo
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Nombre del estadio"}),
            "capacidad":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Capacidad"}),
            "espacio":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Capacidad"}),

            }



class actuestadioforms (forms.ModelForm):
    class Meta:
        model = Equipo
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre de la ciudad"}),
            "equipos": forms.Select(attrs={"class":"form-select form-control"}),
            "equipos": forms.Select(attrs={"class":"form-select form-control"}),
            }

remedial2/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import jugadorforms, actujugadorforms, crearequipoforms, actuequipoforms, crearestadioforms, actuestadioforms



# Create your views here.


##J U G A D O R E S 
class listajugadores (generic.View):
    template_name = "core/jugador/listajugadores.html"
    context = {}

    def get(self, request, *args, **kwargs):
        jugador =  Jugador.objects.all()
        self.context = {
            "jugador": jugador
        }
        return render(request, self.template_name,self.context)
    
class crearjugador(generic.CreateView):
    template_name = "core/jugador/crearjugador.html"
    model = Jugador
    form_class = jugadorforms
    success_url = reverse_lazy("core:listajugadores")

class detallesjugador (generic.DetailView):
    template_name = "core/jugador/detallesjugador.html"
    model = Jugador

class actuajugador (generic.UpdateView):
    template_name = "core/jugador/actujugador.html"
    model = Jugador
    form_class = actujugadorforms
    success_url = reverse_lazy("core:listajugadores")

class borrarjugador (generic.DeleteView):
    template_name = "core/jugador/borrarjugador.html"
    model = Jugador
    success_url = reverse_lazy("core:listajugadores")
############## 

##E Q U I P O S 
class listaequipos (generic.View):
    template_name = "core/equipo/listaequipos.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipo =  Equipo.objects.all()
        self.context = {
            "equipos": equipo
        }
        return render(request, self.template_name,self.context)
    
class crearequipos(generic.CreateView):
    template_name = "core/equipo/crearequipo.html"
    model = Equipo
    form_class = crearequipoforms
    success_url = reverse_lazy("core:listaequipos")

class detallesquipo (generic.DetailView):
    template_name = "core/equipo/detallesequipo.html"
    model = Equipo

class actuequipo (generic.UpdateView):
    template_name = "core/equipo/actuequipo.html"
    model = Equipo
    form_class = actuequipoforms
    success_url = reverse_lazy("core:listaequipos")

class borrarequipo (generic.DeleteView):
    template_name = "core/equipo/borrarequipo.html"
    model = Equipo
    success_url = reverse_lazy("core:listaequipos")

############## 

## E S T A D I O S 
class listaestadios (generic.View):
    template_name = "core/estadio/listaestadios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        estadio =  Estadio.objects.all()
        self.context = {
            "estadios": estadio
        }
        return render(request, self.template_name,self.context)
    
class crearestadio(generic.CreateView):
    template_name = "core/estadio/crearestadio.html"
    model = Estadio
    form_class = crearestadioforms
    success_url = reverse_lazy("core:listaestadios")

class detallesestadio (generic.DetailView):
    template_name = "core/estadio/detallesestadio.html"
    model = Estadio

class actuestadio (generic.UpdateView):
    template_name = "core/estadio/actuestadio.html"
    model = Estadio
    form_class = actuestadioforms
    success_url = reverse_lazy("core:listaestadios")

class borrarestadio (generic.DeleteView):
    template_name = "core/estadio/borrarestadio.html"
    model = Estadio
    success_url = reverse_lazy("core:listaestadios")

remedial2/templates/core/equipo/actuequipo.html
{% extends "base/base.html" %}

{% block title %}
Actualizar equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar equipo</button>
        <a href="{% url 'core:listaequipos' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

remedial2/templates/core/equipo/borrarequipo.html
{% extends "base/base.html" %}

{% block title %}
Borrar equipo
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Seguro de borrar: {{ object.Nombre }}?
        <button type="submit" class="btn btn-outline-danger">Borrar equipo</button>
        <a href="{% url 'core:listaequipos' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

remedial2/templates/core/equipo/crearequipo.html
{% extends "base/base.html" %}

{% block title %}
Crear un equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Agregar equipo</button>
        <a href="{% url 'core:listaequipos' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>


    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock content %}

remedial2/templates/core/equipo/detallesequipo.html
{% extends "base/base.html" %}

{% block title %}
Detalles de equipo
{% endblock title %}


{% block content %}
<h1>Nombre: </h1>{{ object.Nombre }}
<br>
<h1>ID: </h1>{{ object.id }}
  <a href="{% url 'core:listaequipos' %}">Regresar</a>
{% endblock content %}

remedial2/templates/core/equipo/listaequipos.html
{% extends 'base/base.html' %}

{% block title %} lista de equipos {% endblock title %}

{% block content %}


    <a href="{% url 'core:crearequipo' %}" class="btn btn-outline-success form-control">Crear nuevo equipo</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>Nombre</th>
            <th></th>
            <th>Acciones</th>
            <th></th>

        </thead>
        <tbody>
            {% for equipo in equipo %}
                <tr>
                    <td>{{ equipo.id }}</td>
                    <td>{{ equipo.Nombre }}</td>
                    <td><a href="{% url 'core:detallesequipo' equipo.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:actuequipo' equipo.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:borrarequipo' equipo.id %}" class="btn btn-outline-danger">Borrar</a></td>

                </tr>
            {% endfor %}
        </tbody>
    </table>
   
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock content %}